### ISSUE TITLE
Add option to silent warnings

### ISSUE THREAD

**Issue by ambs** [ambs/Text-BibTeX#12]
Some warnings from the C library are relevant. Some others, might not.
the `warning: overriding existing definition of macro x` might be useful on situations, but some others, is just annoying.

An option to be more or less verbose would be nice.

**Comment by plk** [comment]
It will be hard to provide an option for this, given how it's coded in btparse and how btparse doesn't to perlIO. Perhaps it could just be removed with a note in the docs saying that macro redefinitions silently overwrite?

**Comment by ambs** [comment]
Well, did the think in other way. added an option to reset all macros every time a new BibTeX::File is loaded. So, for now, closing this ;)
