### ISSUE TITLE
Problem with double last name parsing

### ISSUE THREAD

**Issue by kwwette** [ambs/Text-BibTeX#21]
There appears to be a problem with parsing double last names, which in some cases produces an "internal error: bad token join method" error. I've pushed a branch reproducing the problem here:

https://github.com/kwwette/Text-BibTeX/tree/nameformat-bug

Note that since the error comes from accessing out-of-bounds memory, the test doesn't fail every time, but if you run "./Build test" a few times it should fail.

For completeness the patch is also here:

https://gist.github.com/kwwette/d07dee95faa8cc0522fb3d4b3cb82bbc

**Comment by ambs** [comment]
what OS are you using? using my Linux I can't make it crash (already run the test more than 30 times :))

**Comment by kwwette** [comment]
$ uname -a
Linux celeris 4.8.0-58-generic #63~16.04.1-Ubuntu SMP Mon Jun 26 18:08:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

How strange. Maybe the failure is in some other library? Maybe a different compiler, e.g. your compiler might be zero-initializing memory which would cause the code not to crash.

**Comment by ambs** [comment]
not much different:

Linux diabelli 4.8.0-58-generic #63~16.04.1-Ubuntu SMP Mon Jun 26 18:08:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ambs** [comment]
wait...

**Comment by ambs** [comment]
wrong branch. slap me hard. Sorry

**Comment by kwwette** [comment]
No problem :)

**Comment by ambs** [comment]
Do you still have the original patch you suggested? Just out of curiosity...

**Comment by ambs** [comment]
Just because I think you did the correct fix (but with your comment I analyzed wrongly the situation)

**Comment by ambs** [comment]
Just committed the patch, and releasing version 0.81.

**Comment by kwwette** [comment]
Oh great, thanks very much!

**Comment by ambs** [comment]
Thank YOU! :)
