### ISSUE TITLE
t/unlimited.t test failing on non-x86 arch

### ISSUE THREAD

**Issue by cbm755** [ambs/Text-BibTeX#22]
I'm packaging for Fedora.  The new unlimited.t test seems to be failed on arm, powerpc and "aarch64".
````
t/bib.t ......... ok
t/from_file.t ... ok
t/macro.t ....... ok
t/modify.t ...... ok
t/nameformat.t .. ok
t/namelist.t .... ok
t/names.t ....... ok
t/output.t ...... ok
t/parse.t ....... ok
t/parse_f.t ..... ok
t/parse_s.t ..... ok
t/purify.t ...... ok
t/unlimited.t ... 
All 4 subtests passed 
Test Summary Report
-------------------
t/unlimited.t (Wstat: 139 Tests: 4 Failed: 0)
  Non-zero wait status: 139
Files=13, Tests=544,  6 wallclock secs ( 0.29 usr  0.08 sys +  4.68 cusr  0.75 csys =  5.80 CPU)
Result: FAIL
Failed 1/13 test programs. 0/544 subtests failed.
````
Will see if I can dig a little deeper...

**Comment by cbm755** [comment]
The warning seems to be generated correct.  But this:
````
t/unlimited.t (Wstat: 139 Tests: 4 Failed: 0)
  Non-zero wait status: 139
````
seems to mean perl segfaults (after the test passes I think).

If I shorten the number of the "F"s in unlimited.bib, then this problem goes away:
````
t/bib.t ......... ok     
t/from_file.t ... ok     
t/macro.t ....... ok     
t/modify.t ...... ok     
t/nameformat.t .. ok     
t/namelist.t .... ok     
t/names.t ....... ok     
t/output.t ...... ok     
t/parse.t ....... ok     
t/parse_f.t ..... ok     
t/parse_s.t ..... ok     
t/purify.t ...... ok       
t/unlimited.t ... ok   
All tests successful.
Files=13, Tests=544,  8 wallclock secs ( 0.40 usr  0.08 sys +  6.54 cusr  0.58 csys =  7.60 CPU)
Result: PASS
````

**Comment by ambs** [comment]
Hi. What version are you using? 0.82 or 0.83?

**Comment by ambs** [comment]
OK, I got cpan testers reports on a broken 0.83 too. Damn. Will try to fix it asap.

**Comment by cbm755** [comment]
Yes on 0.83, sorry for not saying so.  I have shell access to the arm box if there is some debugging that would help

**Comment by ambs** [comment]
Thanks, trying to understand the issue with my raspberry pi :)

**Comment by ambs** [comment]
Can you please test c2e4e0a in your ARM?
Thank you

**Comment by cbm755** [comment]
Yes, 533cc6d75343f859f4ee0fb39f42045395408a seems to have fixed it on arm.  I haven't tried the other arches yet...

**Comment by ambs** [comment]
I tried some. Will release. CPAN testers will also help. If you wish, you can wait a day and I'll tell you how did it go.

**Comment by ambs** [comment]
ok, some failures on freebsd, releasing 0.85.

**Comment by ambs** [comment]
looks good: http://matrix.cpantesters.org/?dist=Text-BibTeX

Closing ticket. Thanks for your report!
