### ISSUE TITLE
Release 

### ISSUE THREAD

**Issue by leezu** [ambs/Text-BibTeX#31]
Hi, following ef299ab4 it would be great to have a new release so that the fixed header files get distributed.
Thank you!

**Comment by ambs** [comment]
Hi. https://metacpan.org/pod/Text::BibTeX should have that code. Can you please confirm?

**Comment by leezu** [comment]
I just downloaded https://cpan.metacpan.org/authors/id/A/AM/AMBS/Text-BibTeX-0.86.tar.gz but it does not contain the updated `btparse.h`

**Comment by ambs** [comment]
I did :hankey:
Please confirm with https://metacpan.org/release/AMBS/Text-BibTeX-0.87

**Comment by leezu** [comment]
No worries. Text-BibTeX-0.87 contains the correct files, thanks!

By the way, would you support introducing a separate build setup for `btparse`? Currently building the whole Text-BibTeX with `Build.PL` is required to obtain `libbtparse.so`. Is there a way to tell  `Build.PL` to create a static `libbtparse.a`?

**Comment by ambs** [comment]
@leezu I was doing so (you still can find a btparse file somewhere in CPAN) but afaik nobody was using it. Maintaining a separate configure/make/make install was too troublesome...
