### ISSUE TITLE
Buid on Windows10 and MSVC

### ISSUE THREAD

**Issue by gitdevmod** [ambs/Text-BibTeX#35]
Hi,

Building Text::BibTex with MSVC fails with:
`
cpan[2]> install Text::BibTeX
Running install for module 'Text::BibTeX'
Checksum for C:\Users\user\.cpan\sources\authors\id\A\AM\AMBS\Text-BibTeX-0.88.tar.gz ok
Scanning cache C:\Users\user\.cpan\build for sizes
............................................................................DONE
'YAML' not installed, will not store persistent state
Configuring A/AM/AMBS/Text-BibTeX-0.88.tar.gz with Build.PL
compilet-5SWjN.c
   Création de la bibliothèque compilet.lib et de l'objet compilet.exp
Génération de code en cours
Fin de la génération du code
libbtparse.dll will be installed in C:\CraftRoot\dev-utils\bin
Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Text-BibTeX' version '0.88'
  AMBS/Text-BibTeX-0.88.tar.gz
  C:\CraftRoot\bin\perl.exe Build.PL -- OK
Running Build for A/AM/AMBS/Text-BibTeX-0.88.tar.gz
Building Text-BibTeX
Generating script 'C:\Users\user\AppData\Local\Temp\2pAmAg7MZG\library.ccs'
cl -nologo -c @"C:\Users\user\AppData\Local\Temp\2pAmAg7MZG\library.ccs" -Fo"C:\Users\user\AppData\Local\Temp\2pAmAg7MZG\library.obj" "C:\Users\user\AppData\Local\Temp\2pAmAg7MZG\library.c"
library.c
Generating script 'C:\Users\user\AppData\Local\Temp\2pAmAg7MZG\test.ccs'
cl -nologo -c @"C:\Users\user\AppData\Local\Temp\2pAmAg7MZG\test.ccs" -Fo"C:\Users\user\AppData\Local\Temp\2pAmAg7MZG\test.obj" "C:\Users\user\AppData\Local\Temp\2pAmAg7MZG\test.c"
test.c
Microsoft (R) Incremental Linker Version 14.28.29336.0
Copyright (C) Microsoft Corporation.  All rights reserved.

LINK : warning LNK4044: option '/shared' non reconnue ; ignorée
LINK : warning LNK4044: option '/o' non reconnue ; ignorée
LINK : fatal error LNK1181: impossible d'ouvrir le fichier en entrée 'C:\Users\user\AppData\Local\Temp\2pAmAg7MZG\libfoo.dll'
Checking for alloca.h... Checking for cc... compilet-Ql5nu.c
   Création de la bibliothèque compilet.lib et de l'objet compilet.exp
Génération de code en cours
Fin de la génération du code
cl
no
Checking for vsnprintf... no
Checking for strlcat... no
Creating new 'btparse/src/bt_config.h' from 'btparse/src/bt_config.h.in'.

** Creating Manpages

** Compiling C files
Generating script 'btparse\progs\args.ccs'
cl -nologo -c @"btparse\progs\args.ccs" -Fo"btparse\progs\args.o" "btparse\progs\args.c"
args.c
Generating script 'btparse\progs\biblex.ccs'
cl -nologo -c @"btparse\progs\biblex.ccs" -Fo"btparse\progs\biblex.o" "btparse\progs\biblex.c"
biblex.c
btparse\progs\biblex.c(52): warning C4013: 'exit' non défini(e) ; extern retournant int pris par défaut
Generating script 'btparse\progs\bibparse.ccs'
cl -nologo -c @"btparse\progs\bibparse.ccs" -Fo"btparse\progs\bibparse.o" "btparse\progs\bibparse.c"
bibparse.c
Generating script 'btparse\progs\dumpnames.ccs'
cl -nologo -c @"btparse\progs\dumpnames.ccs" -Fo"btparse\progs\dumpnames.o" "btparse\progs\dumpnames.c"
dumpnames.c
Generating script 'btparse\progs\getopt.ccs'
cl -nologo -c @"btparse\progs\getopt.ccs" -Fo"btparse\progs\getopt.o" "btparse\progs\getopt.c"
getopt.c
Generating script 'btparse\progs\getopt1.ccs'
cl -nologo -c @"btparse\progs\getopt1.ccs" -Fo"btparse\progs\getopt1.o" "btparse\progs\getopt1.c"
getopt1.c
Generating script 'btparse\src\bibtex.ccs'
cl -nologo -c @"btparse\src\bibtex.ccs" -Fo"btparse\src\bibtex.o" "btparse\src\bibtex.c"
bibtex.c
C:\Users\user\.cpan\build\Text-BibTeX-0.88-2\btparse\src\../pccts/ast.c(82): warning C4013: 'exit' non défini(e) ; extern retournant int pris par défaut
C:\Users\user\.cpan\build\Text-BibTeX-0.88-2\btparse\src\../pccts/ast.c(192): error C2061: erreur de syntaxe : identificateur 'va_dcl'
C:\Users\user\.cpan\build\Text-BibTeX-0.88-2\btparse\src\../pccts/ast.c(192): error C2059: erreur de syntaxe : ';'C:\Users\user\.cpan\build\Text-BibTeX-0.88-2\btparse\src\../pccts/ast.c(194): error C2449: trouvé '{' au niveau de la portée du fichier (en-tête de fonction manquant ?)
C:\Users\user\.cpan\build\Text-BibTeX-0.88-2\btparse\src\../pccts/ast.c(203): warning C4003: pas assez d'arguments pour l'appel de macro de type fonction '__crt_va_start'
C:\Users\user\.cpan\build\Text-BibTeX-0.88-2\btparse\src\../pccts/ast.c(221): error C2059: erreur de syntaxe : '}'C:\Users\user\.cpan\build\Text-BibTeX-0.88-2\btparse\src\../pccts/ast.c(230): error C2449: trouvé '{' au niveau de la portée du fichier (en-tête de fonction manquant ?)
C:\Users\user\.cpan\build\Text-BibTeX-0.88-2\btparse\src\../pccts/ast.c(247): error C2059: erreur de syntaxe : '}'C:\Users\user\.cpan\build\Text-BibTeX-0.88-2\btparse\src\../pccts/ast.c(255): error C2449: trouvé '{' au niveau de la portée du fichier (en-tête de fonction manquant ?)
C:\Users\user\.cpan\build\Text-BibTeX-0.88-2\btparse\src\../pccts/ast.c(260): error C2059: erreur de syntaxe : '}'error building dll file from 'btparse/src/bibtex.c' at C:/CraftRoot/lib/ExtUtils/CBuilder/Platform/Windows.pm line 128.
  AMBS/Text-BibTeX-0.88.tar.gz
  C:\CraftRoot\bin\perl.exe ./Build -- NOT OK
Failed during this command:
 AMBS/Text-BibTeX-0.88.tar.gz                 : make NO

cpan[3]>
`
Regards

**Comment by ambs** [comment]
I am sorry but I do not use windows nor Microsoft Visual C Compiler. I really can't help.

**Comment by gitdevmod** [comment]
Ok, it's probably just a missing include. Where is coming from "va_dcl" ?

**Comment by ambs** [comment]
Accordingly with google, varargs.h

**Comment by gitdevmod** [comment]
This file exists also with MSVC,
I replaced all occurence of "#ifdef __STDC__" with "#if defined(__STDC__) || defined(_MSC_VER)" for testing.
But it fails at the end with
Use of uninitialized value $LIBEXT in concatenation (.) or string at inc/MyBuilder.pm line 339.

** Creating libbtparse
Use of uninitialized value $LIBEXT in concatenation (.) or string at inc/MyBuilder.pm line 349.
Use of uninitialized value $LIBEXT in concatenation (.) or string at inc/MyBuilder.pm line 350.
Use of uninitialized value $LIBEXT in string eq at inc/MyBuilder.pm line 356.
Can't call method "link" on unblessed reference at inc/MyBuilder.pm line 361.
  AMBS/Text-BibTeX-0.88.tar.gz
  C:\CraftRoot\bin\perl.exe ./Build -- NOT OK
Failed during this command:
 AMBS/Text-BibTeX-0.88.tar.gz                 : make NO

**Comment by ambs** [comment]
It means it couldn't detect that libraries in windows are `.dll` files.

**Comment by gitdevmod** [comment]
I think we can close issue, I do not know how to solve this error.
