### ISSUE TITLE
Build failure: insufficient Config::AutoConf version

### ISSUE THREAD

**Issue by dmacks** [ambs/Text-BibTeX#36]
Text-BibTeX 0.88 on OS X 10.13 with Apple's perl-5.8.12 fails during Build.PL:
```
Can't locate object method "check_func" via package "Config::AutoConf" at inc/MyBuilder.pm line 86.
```
even though I have Config::AutoConf-0.19 installed (Build.PL and META.yml say 0.16 is the minimum). Turns out check_func was not added until 0.306.001. (https://github.com/ambs/Config-AutoConf/compare/0.305...0.306_001)

**Comment by ambs** [comment]
Hi!
Are you able to submit a Pull Request? Ir would be faster to release a new version with a fix.
Thanks

**Comment by ambs** [comment]
v0.89 uploaded to cpan. Hopefully fixing this.
